[package]
name = "pomod"
version = "0.1.0"
authors = ["liquid600pgm <liquidekgaming@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
signal = "0.7.0"
notify-rust = "3.6.3"
