[package]
name = "pomod"
version = "0.1.0"
authors = ["liquid600pgm <liquidekgaming@gmail.com>"]
edition = "2018"

[dependencies]
signal = "0.7.0"
notify-rust = "3.6.3"

[profile.release]
lto = true
codegen-units = 1
